// Client-safe helpers kept separate from the server-side Zod schemas.
import type { Roadmap } from './security';

const CLIENT_NODE_ID = /^[a-z0-9-]{1,64}$/;
const CLIENT_COLOR = /^#[0-9a-fA-F]{6}$/;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value && typeof value === 'object' && !Array.isArray(value));

const boundedString = (value: unknown, max: number): string | null =>
  typeof value === 'string' && value.length > 0 && value.length <= max ? value : null;

export function parseClientRoadmap(value: unknown): Roadmap | null {
  if (!isRecord(value)) return null;
  const id = boundedString(value.id, 64);
  const title = boundedString(value.title, 80);
  const description = boundedString(value.description, 300);
  const icon = typeof value.icon === 'string' && value.icon.length <= 4 ? value.icon : null;
  const color = typeof value.color === 'string' && CLIENT_COLOR.test(value.color) ? value.color : null;
  const rawNodes = Array.isArray(value.nodes) && value.nodes.length >= 1 && value.nodes.length <= 200 ? value.nodes : null;
  if (!id || !CLIENT_NODE_ID.test(id) || !title || !description || icon === null || !color || !rawNodes) return null;

  const seenIds = new Set<string>();
  const nodes = [];
  let rootCount = 0;
  for (const rawNode of rawNodes) {
    if (!isRecord(rawNode)) return null;
    const nodeId = boundedString(rawNode.id, 64);
    const label = boundedString(rawNode.label, 80);
    const nodeType = rawNode.type;
    const status = rawNode.status;
    const parentId = rawNode.parentId;
    if (!nodeId || !CLIENT_NODE_ID.test(nodeId) || seenIds.has(nodeId) || !label) return null;
    if (nodeType !== 'root' && nodeType !== 'topic' && nodeType !== 'optional') return null;
    if (status !== 'todo' && status !== 'in-progress' && status !== 'done' && status !== 'bookmarked') return null;
    if (parentId !== null && (typeof parentId !== 'string' || !CLIENT_NODE_ID.test(parentId))) return null;
    if (nodeType === 'root') {
      rootCount += 1;
      if (parentId !== null) return null;
    } else if (parentId === null) {
      return null;
    }
    seenIds.add(nodeId);
    nodes.push({ id: nodeId, label, parentId, status, type: nodeType });
  }

  if (rootCount !== 1 || nodes.some((node) => node.parentId !== null && !seenIds.has(node.parentId))) return null;
  return { id, title, description, icon, color, nodes } as Roadmap;
}


export async function sanitizeHtml(htmlContent: string): Promise<string> {
  if (typeof window === 'undefined') return '';
  const { default: DOMPurify } = await import('dompurify');

  return DOMPurify.sanitize(htmlContent, {
    ALLOWED_TAGS: [
      'h2', 'h3', 'h4', 'p', 'ul', 'ol', 'li', 'strong', 'em',
      'code', 'pre', 'a', 'table', 'thead', 'tbody', 'tr', 'th', 'td',
      'blockquote', 'hr', 'br', 'span',
    ],
    ALLOWED_ATTR: ['href', 'class', 'id', 'target', 'rel'],
    ALLOW_DATA_ATTR: false,
    FORCE_BODY: false,
  } as Parameters<typeof DOMPurify.sanitize>[1]);
}

/**
 * Robustly parses JSON generated by AI, removing conversational wrappers,
 * trailing commas, and JavaScript-style comments before parsing.
 */
export function cleanAndParseJSON(rawText: string): any {
  const firstBrace = rawText.indexOf('{');
  const firstBracket = rawText.indexOf('[');
  let startIdx = -1;
  let endIdx = -1;

  if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
    startIdx = firstBrace;
    endIdx = rawText.lastIndexOf('}');
  } else if (firstBracket !== -1) {
    startIdx = firstBracket;
    endIdx = rawText.lastIndexOf(']');
  }

  if (startIdx === -1 || endIdx === -1) {
    throw new Error('No valid JSON structure found in AI response.');
  }

  let jsonStr = rawText.substring(startIdx, endIdx + 1);
  jsonStr = jsonStr.replace(/,(\s*[\]}])/g, '$1');
  jsonStr = jsonStr.replace(/\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm, '$1');
  return JSON.parse(jsonStr);
}
