// Client-safe helpers kept separate from the server-side Zod schemas.

export async function sanitizeHtml(htmlContent: string): Promise<string> {
  if (typeof window === 'undefined') return '';
  const { default: DOMPurify } = await import('dompurify');

  return DOMPurify.sanitize(htmlContent, {
    ALLOWED_TAGS: [
      'h2', 'h3', 'h4', 'p', 'ul', 'ol', 'li', 'strong', 'em',
      'code', 'pre', 'a', 'table', 'thead', 'tbody', 'tr', 'th', 'td',
      'blockquote', 'hr', 'br', 'span',
    ],
    ALLOWED_ATTR: ['href', 'class', 'id', 'target', 'rel'],
    ALLOW_DATA_ATTR: false,
    FORCE_BODY: false,
  } as Parameters<typeof DOMPurify.sanitize>[1]);
}

/**
 * Robustly parses JSON generated by AI, removing conversational wrappers,
 * trailing commas, and JavaScript-style comments before parsing.
 */
export function cleanAndParseJSON(rawText: string): any {
  const firstBrace = rawText.indexOf('{');
  const firstBracket = rawText.indexOf('[');
  let startIdx = -1;
  let endIdx = -1;

  if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
    startIdx = firstBrace;
    endIdx = rawText.lastIndexOf('}');
  } else if (firstBracket !== -1) {
    startIdx = firstBracket;
    endIdx = rawText.lastIndexOf(']');
  }

  if (startIdx === -1 || endIdx === -1) {
    throw new Error('No valid JSON structure found in AI response.');
  }

  let jsonStr = rawText.substring(startIdx, endIdx + 1);
  jsonStr = jsonStr.replace(/,(\s*[\]}])/g, '$1');
  jsonStr = jsonStr.replace(/\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm, '$1');
  return JSON.parse(jsonStr);
}
